apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---

apiVersion: v1
kind: Service
metadata:
  name: controller-0
  namespace: kafka
  labels:
    app: kafka
    role: controller
    nodeId: "0"
spec:
  selector:
    app: kafka
    role: controller
    nodeId: "0"
  ports:
    - name: controller
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: controller-1
  namespace: kafka
  labels:
    app: kafka
    role: controller
    nodeId: "1"
spec:
  selector:
    app: kafka
    role: controller
    nodeId: "1"
  ports:
    - name: controller
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: controller-2
  namespace: kafka
  labels:
    app: kafka
    role: controller
    nodeId: "2"
spec:
  selector:
    app: kafka
    role: controller
    nodeId: "2"
  ports:
    - name: controller
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: broker-0
  namespace: kafka
  labels:
    app: kafka
    role: broker
    nodeId: "10"
spec:
  selector:
    app: kafka
    role: broker
    nodeId: "10"
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: broker-1
  namespace: kafka
  labels:
    app: kafka
    role: broker
    nodeId: "11"
spec:
  selector:
    app: kafka
    role: broker
    nodeId: "11"
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: broker-2
  namespace: kafka
  labels:
    app: kafka
    role: broker
    nodeId: "12"
spec:
  selector:
    app: kafka
    role: broker
    nodeId: "12"
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
---
# PVCs (controllers)
############################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-data-0
  namespace: kafka
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-data-1
  namespace: kafka
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-data-2
  namespace: kafka
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 5Gi
---
# PVCs (brokers)
############################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-data-0
  namespace: kafka
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-data-1
  namespace: kafka
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-data-2
  namespace: kafka
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 5Gi
---
############################################################
# ConfigMaps: server.properties
# FIX: log.dirs points to a subdirectory so ext4's lost+found
# at the filesystem root doesn't break Kafka.
############################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-0-config
  namespace: kafka
data:
  server.properties: |
    process.roles=controller
    node.id=0
    controller.quorum.voters=0@controller-0.kafka.svc:9093,1@controller-1.kafka.svc:9093,2@controller-2.kafka.svc:9093
    controller.listener.names=CONTROLLER
    listeners=CONTROLLER://0.0.0.0:9093
    listener.security.protocol.map=CONTROLLER:PLAINTEXT
    log.dirs=/var/lib/kafka/data/logs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-1-config
  namespace: kafka
data:
  server.properties: |
    process.roles=controller
    node.id=1
    controller.quorum.voters=0@controller-0.kafka.svc:9093,1@controller-1.kafka.svc:9093,2@controller-2.kafka.svc:9093
    controller.listener.names=CONTROLLER
    listeners=CONTROLLER://0.0.0.0:9093
    listener.security.protocol.map=CONTROLLER:PLAINTEXT
    log.dirs=/var/lib/kafka/data/logs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-2-config
  namespace: kafka
data:
  server.properties: |
    process.roles=controller
    node.id=2
    controller.quorum.voters=0@controller-0.kafka.svc:9093,1@controller-1.kafka.svc:9093,2@controller-2.kafka.svc:9093
    controller.listener.names=CONTROLLER
    listeners=CONTROLLER://0.0.0.0:9093
    listener.security.protocol.map=CONTROLLER:PLAINTEXT
    log.dirs=/var/lib/kafka/data/logs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-0-config
  namespace: kafka
data:
  server.properties: |
    process.roles=broker
    node.id=10
    controller.quorum.voters=0@controller-0.kafka.svc:9093,1@controller-1.kafka.svc:9093,2@controller-2.kafka.svc:9093
    controller.listener.names=CONTROLLER

    listeners=PLAINTEXT://0.0.0.0:9092
    advertised.listeners=PLAINTEXT://broker-0.kafka.svc:9092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    inter.broker.listener.name=PLAINTEXT

    log.dirs=/var/lib/kafka/data/logs

    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    min.insync.replicas=2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-1-config
  namespace: kafka
data:
  server.properties: |
    process.roles=broker
    node.id=11
    controller.quorum.voters=0@controller-0.kafka.svc:9093,1@controller-1.kafka.svc:9093,2@controller-2.kafka.svc:9093
    controller.listener.names=CONTROLLER

    listeners=PLAINTEXT://0.0.0.0:9092
    advertised.listeners=PLAINTEXT://broker-1.kafka.svc:9092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    inter.broker.listener.name=PLAINTEXT

    log.dirs=/var/lib/kafka/data/logs

    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    min.insync.replicas=2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-2-config
  namespace: kafka
data:
  server.properties: |
    process.roles=broker
    node.id=12
    controller.quorum.voters=0@controller-0.kafka.svc:9093,1@controller-1.kafka.svc:9093,2@controller-2.kafka.svc:9093
    controller.listener.names=CONTROLLER

    listeners=PLAINTEXT://0.0.0.0:9092
    advertised.listeners=PLAINTEXT://broker-2.kafka.svc:9092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    inter.broker.listener.name=PLAINTEXT

    log.dirs=/var/lib/kafka/data/logs

    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    min.insync.replicas=2
---
############################################################
# Deployments: Controllers (controller-only)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-0
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: controller
      nodeId: "0"
  template:
    metadata:
      labels:
        app: kafka
        role: controller
        nodeId: "0"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: kafka
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/confluent-kafka:latest
          imagePullPolicy: Always
          ports:
            - name: controller
              containerPort: 9093
          env:
            - name: CLUSTER_ID
              value: "P1VHphRWRlqnf6WKhHjMng"
          command: ["/bin/sh", "-ec"]
          args:
            - |
              kafka-storage format -t "${CLUSTER_ID}" -c /etc/kafka/server.properties --ignore-formatted
              exec kafka-server-start /etc/kafka/server.properties
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
            - name: config
              mountPath: /etc/kafka
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: controller-data-0
        - name: config
          configMap:
            name: controller-0-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: controller
      nodeId: "1"
  template:
    metadata:
      labels:
        app: kafka
        role: controller
        nodeId: "1"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: kafka
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/confluent-kafka:latest
          imagePullPolicy: Always
          ports:
            - name: controller
              containerPort: 9093
          env:
            - name: CLUSTER_ID
              value: "P1VHphRWRlqnf6WKhHjMng"
          command: ["/bin/sh", "-ec"]
          args:
            - |
              kafka-storage format -t "${CLUSTER_ID}" -c /etc/kafka/server.properties --ignore-formatted
              exec kafka-server-start /etc/kafka/server.properties
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
            - name: config
              mountPath: /etc/kafka
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: controller-data-1
        - name: config
          configMap:
            name: controller-1-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-2
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: controller
      nodeId: "2"
  template:
    metadata:
      labels:
        app: kafka
        role: controller
        nodeId: "2"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: kafka
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/confluent-kafka:latest
          imagePullPolicy: Always
          ports:
            - name: controller
              containerPort: 9093
          env:
            - name: CLUSTER_ID
              value: "P1VHphRWRlqnf6WKhHjMng"
          command: ["/bin/sh", "-ec"]
          args:
            - |
              kafka-storage format -t "${CLUSTER_ID}" -c /etc/kafka/server.properties --ignore-formatted
              exec kafka-server-start /etc/kafka/server.properties
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
            - name: config
              mountPath: /etc/kafka
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: controller-data-2
        - name: config
          configMap:
            name: controller-2-config
---
############################################################
# Deployments: Brokers (broker-only)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-0
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: broker
      nodeId: "10"
  template:
    metadata:
      labels:
        app: kafka
        role: broker
        nodeId: "10"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: kafka
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/confluent-kafka:latest
          imagePullPolicy: Always
          ports:
            - name: broker
              containerPort: 9092
          env:
            - name: CLUSTER_ID
              value: "P1VHphRWRlqnf6WKhHjMng"
          command: ["/bin/sh", "-ec"]
          args:
            - |
              kafka-storage format -t "${CLUSTER_ID}" -c /etc/kafka/server.properties --ignore-formatted
              exec kafka-server-start /etc/kafka/server.properties
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
            - name: config
              mountPath: /etc/kafka
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 18
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: broker-data-0
        - name: config
          configMap:
            name: broker-0-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: broker
      nodeId: "11"
  template:
    metadata:
      labels:
        app: kafka
        role: broker
        nodeId: "11"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: kafka
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/confluent-kafka:latest
          imagePullPolicy: Always
          ports:
            - name: broker
              containerPort: 9092
          env:
            - name: CLUSTER_ID
              value: "P1VHphRWRlqnf6WKhHjMng"
          command: ["/bin/sh", "-ec"]
          args:
            - |
              kafka-storage format -t "${CLUSTER_ID}" -c /etc/kafka/server.properties --ignore-formatted
              exec kafka-server-start /etc/kafka/server.properties
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
            - name: config
              mountPath: /etc/kafka
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 18
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: broker-data-1
        - name: config
          configMap:
            name: broker-1-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-2
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      role: broker
      nodeId: "12"
  template:
    metadata:
      labels:
        app: kafka
        role: broker
        nodeId: "12"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: kafka
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/confluent-kafka:latest
          imagePullPolicy: Always
          ports:
            - name: broker
              containerPort: 9092
          env:
            - name: CLUSTER_ID
              value: "P1VHphRWRlqnf6WKhHjMng"
          command: ["/bin/sh", "-ec"]
          args:
            - |
              kafka-storage format -t "${CLUSTER_ID}" -c /etc/kafka/server.properties --ignore-formatted
              exec kafka-server-start /etc/kafka/server.properties
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
            - name: config
              mountPath: /etc/kafka
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 18
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: broker-data-2
        - name: config
          configMap:
            name: broker-2-config