# Kafka Proxy 0 (mTLS)
############################################################
apiVersion: v1
kind: Service
metadata:
  name: kafka-proxy-0
  namespace: kafka
  labels:
    app: kafka-proxy
    instance: "0"
spec:
  selector:
    app: kafka-proxy
    instance: "0"
  ports:
    - name: kafka-mtls
      protocol: TCP
      port: 9094
      targetPort: 9094
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-proxy-0
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-proxy
      instance: "0"
  template:
    metadata:
      labels:
        app: kafka-proxy
        instance: "0"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: kafka-proxy
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/kafka-proxy-fips:0.4.3
          imagePullPolicy: IfNotPresent
          args:
            - server
            - --dynamic-listeners-disable

            - --bootstrap-server-mapping
            - broker-0.kafka.svc:9092,0.0.0.0:9094,kafka-proxy-0.kafka.svc:9094

            - --dial-address-mapping
            - broker-0.kafka.svc:9092,broker-0.kafka.svc:9092
            - --dial-address-mapping
            - broker-1.kafka.svc:9092,broker-1.kafka.svc:9092
            - --dial-address-mapping
            - broker-2.kafka.svc:9092,broker-2.kafka.svc:9092

            - --external-server-mapping
            - broker-0.kafka.svc:9092,kafka-proxy-0.kafka.svc:9094
            - --external-server-mapping
            - broker-1.kafka.svc:9092,kafka-proxy-1.kafka.svc:9094
            - --external-server-mapping
            - broker-2.kafka.svc:9092,kafka-proxy-2.kafka.svc:9094

            - --http-listen-address
            - 0.0.0.0:9080

            - --proxy-listener-tls-enable
            - --proxy-listener-cert-file
            - /tls/tls.crt
            - --proxy-listener-key-file
            - /tls/tls.key
            - --proxy-listener-ca-chain-cert-file
            - /tls/ca.crt

            - --log-level
            - info
          ports:
            - name: kafka-mtls
              containerPort: 9094
            - name: http
              containerPort: 9080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: mtls
              mountPath: /tls
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9094
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 9094
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
      volumes:
        - name: mtls
          secret:
            secretName: kafka-proxy-mtls
---
# Kafka Proxy 1 (mTLS)
############################################################
apiVersion: v1
kind: Service
metadata:
  name: kafka-proxy-1
  namespace: kafka
  labels:
    app: kafka-proxy
    instance: "1"
spec:
  selector:
    app: kafka-proxy
    instance: "1"
  ports:
    - name: kafka-mtls
      protocol: TCP
      port: 9094
      targetPort: 9094
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-proxy-1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-proxy
      instance: "1"
  template:
    metadata:
      labels:
        app: kafka-proxy
        instance: "1"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: kafka-proxy
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/kafka-proxy-fips:0.4.3
          imagePullPolicy: IfNotPresent
          args:
            - server
            - --dynamic-listeners-disable

            - --bootstrap-server-mapping
            - broker-1.kafka.svc:9092,0.0.0.0:9094,kafka-proxy-1.kafka.svc:9094

            - --dial-address-mapping
            - broker-0.kafka.svc:9092,broker-0.kafka.svc:9092
            - --dial-address-mapping
            - broker-1.kafka.svc:9092,broker-1.kafka.svc:9092
            - --dial-address-mapping
            - broker-2.kafka.svc:9092,broker-2.kafka.svc:9092

            - --external-server-mapping
            - broker-0.kafka.svc:9092,kafka-proxy-0.kafka.svc:9094
            - --external-server-mapping
            - broker-1.kafka.svc:9092,kafka-proxy-1.kafka.svc:9094
            - --external-server-mapping
            - broker-2.kafka.svc:9092,kafka-proxy-2.kafka.svc:9094

            - --http-listen-address
            - 0.0.0.0:9080

            - --proxy-listener-tls-enable
            - --proxy-listener-cert-file
            - /tls/tls.crt
            - --proxy-listener-key-file
            - /tls/tls.key
            - --proxy-listener-ca-chain-cert-file
            - /tls/ca.crt

            - --log-level
            - info
          ports:
            - name: kafka-mtls
              containerPort: 9094
            - name: http
              containerPort: 9080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: mtls
              mountPath: /tls
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9094
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 9094
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
      volumes:
        - name: mtls
          secret:
            secretName: kafka-proxy-mtls
---
# Kafka Proxy 2 (mTLS)
############################################################
apiVersion: v1
kind: Service
metadata:
  name: kafka-proxy-2
  namespace: kafka
  labels:
    app: kafka-proxy
    instance: "2"
spec:
  selector:
    app: kafka-proxy
    instance: "2"
  ports:
    - name: kafka-mtls
      protocol: TCP
      port: 9094
      targetPort: 9094
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-proxy-2
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-proxy
      instance: "2"
  template:
    metadata:
      labels:
        app: kafka-proxy
        instance: "2"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: kafka-proxy
          image: 452336408843.dkr.ecr.us-west-2.amazonaws.com/kafka-proxy-fips:0.4.3
          imagePullPolicy: IfNotPresent
          args:
            - server
            - --dynamic-listeners-disable

            - --bootstrap-server-mapping
            - broker-2.kafka.svc:9092,0.0.0.0:9094,kafka-proxy-2.kafka.svc:9094

            - --dial-address-mapping
            - broker-0.kafka.svc:9092,broker-0.kafka.svc:9092
            - --dial-address-mapping
            - broker-1.kafka.svc:9092,broker-1.kafka.svc:9092
            - --dial-address-mapping
            - broker-2.kafka.svc:9092,broker-2.kafka.svc:9092

            - --external-server-mapping
            - broker-0.kafka.svc:9092,kafka-proxy-0.kafka.svc:9094
            - --external-server-mapping
            - broker-1.kafka.svc:9092,kafka-proxy-1.kafka.svc:9094
            - --external-server-mapping
            - broker-2.kafka.svc:9092,kafka-proxy-2.kafka.svc:9094

            - --http-listen-address
            - 0.0.0.0:9080

            - --proxy-listener-tls-enable
            - --proxy-listener-cert-file
            - /tls/tls.crt
            - --proxy-listener-key-file
            - /tls/tls.key
            - --proxy-listener-ca-chain-cert-file
            - /tls/ca.crt

            - --log-level
            - info
          ports:
            - name: kafka-mtls
              containerPort: 9094
            - name: http
              containerPort: 9080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: mtls
              mountPath: /tls
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9094
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 9094
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
      volumes:
        - name: mtls
          secret:
            secretName: kafka-proxy-mtls